backend:
  name: github
  repo: LuckyTeamX/wotblog

media_folder: packages/modern-agency/static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: packages/modern-agency/content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list }
      - { name: cover, label: Cover, widget: image }
      - { name: body, label: Body, widget: markdown }